# notestyles
\addfile[input]{<filename>}
\addfile{<filename>}
\begin{definition}{title}
\begin{example}
\begin{exercise}{title}
\begin{indentparagraph}
\begin{sidenote}{title}
\begin{theorem}{title}
\concept{text}
\end{definition}
\end{example}
\end{exercise}
\end{indentparagraph}
\end{sidenote}
\end{theorem}
\question{text}
\nl
\rulebookend
\rulechapterend
